// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/21/2026, 12:09:38 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/home/jsell/code/k-orchestrate/src/dashboard/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/jsell/code/k-orchestrate/src/dashboard/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/jsell/code/k-orchestrate/src/dashboard/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/jsell/code/k-orchestrate/src/dashboard/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/jsell/code/k-orchestrate/src/dashboard/app/plugins/**/*.{js,ts,mjs}","/home/jsell/code/k-orchestrate/src/dashboard/app/composables/**/*.{js,ts,mjs}","/home/jsell/code/k-orchestrate/src/dashboard/app/utils/**/*.{js,ts,mjs}","/home/jsell/code/k-orchestrate/src/dashboard/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/jsell/code/k-orchestrate/src/dashboard/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/jsell/code/k-orchestrate/src/dashboard/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/jsell/code/k-orchestrate/src/dashboard/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;